import "./globals.css";
import type { Metadata } from "next";
import NavBar from "../../components/navbar/NavBar";
import { Inter } from "next/font/google";
import { authOptions } from "./api/auth/[...nextauth]/authOptions";  // TODO DELETE
import { getServerSession } from "next-auth";  // TODO DELETE
import { Provider } from "../../context/provider"; // TODO DELETE

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions); // TODO DELETE
  console.log('session', session); // TODO DELETE
  // TODO DELETE <Provider> tags
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          {children}
          {/* todo****** : prop currentUser needs to be added  */}
          <NavBar />
        </body>
      </Provider>
    </html>
  );
}
